module.exports = [
  {
    ignores: [
      "views/**/*.ejs",
      "**/*.ejs",
      "**/*.html",
      "**/*.htm",
      "node_modules/**",
      "dist/**",
      "build/**",
      "logs/**",
      "scripts/**",
      "public/**",
      ".vscode/**",
      "*.md",
      "*.txt",
      "*.json",
      "*.css",
      "*.webp",
      "*.png",
      "*.jpg",
      "*.jpeg",
      "*.gif",
      "*.webm",
      "*.mp4",
      "*.ico"
    ]
  }
]; 